/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import modele.Connexion;
import vue.MainPage;

/**
 *
 * @author micha
 */
public class Reporting extends JPanel{
    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *

    /**
     * Creates new form ReportingPanel
     */
    public Reporting(Connexion conn) {
        initComponents();
        this.conn = conn;
        this.liste = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        background = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        reportsbg = new javax.swing.JPanel();
        reportPanels = new javax.swing.JTabbedPane();
        report1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        report2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sqlreport = new javax.swing.JPanel();
        requete = new javax.swing.JTextField();
        envoyer = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 450));

        background.setBackground(new java.awt.Color(51, 51, 255));
        background.setPreferredSize(new java.awt.Dimension(700, 450));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Reporting");

        reportsbg.setBackground(new java.awt.Color(255, 255, 255));
        reportsbg.setLayout(new java.awt.CardLayout());

        reportPanels.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N

        report1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel1.setText("Répartition des spécialités des docteurs");

        javax.swing.GroupLayout report1Layout = new javax.swing.GroupLayout(report1);
        report1.setLayout(report1Layout);
        report1Layout.setHorizontalGroup(
            report1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel1)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        report1Layout.setVerticalGroup(
            report1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        reportPanels.addTab("Data 1", report1);

        report2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel2.setText("Répartition des spécialités des docteurs");

        javax.swing.GroupLayout report2Layout = new javax.swing.GroupLayout(report2);
        report2.setLayout(report2Layout);
        report2Layout.setHorizontalGroup(
            report2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report2Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel2)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        report2Layout.setVerticalGroup(
            report2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 320, Short.MAX_VALUE))
        );

        reportPanels.addTab("Data 2", report2);

        sqlreport.setBackground(new java.awt.Color(255, 255, 255));

        requete.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        requete.setText("enter your SQL Request");
        requete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        
        if(this.liste != null)
        {
            // a coder pr recevoir la requete;
        }

        envoyer.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        envoyer.setText("launch");
        envoyer.addActionListener(new Request());

        javax.swing.GroupLayout report3Layout = new javax.swing.GroupLayout(sqlreport);
        sqlreport.setLayout(report3Layout);
        report3Layout.setHorizontalGroup(
            report3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report3Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(requete, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(envoyer)
                .addGap(32, 32, 32))
        );
        report3Layout.setVerticalGroup(
            report3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report3Layout.createSequentialGroup()
                .addGroup(report3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(envoyer, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 314, Short.MAX_VALUE))
        );

        reportPanels.addTab("Custom Data", sqlreport);

        reportsbg.add(reportPanels, "card2");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(292, 292, 292))
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(reportsbg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(title)
                .addContainerGap(409, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                    .addGap(0, 74, Short.MAX_VALUE)
                    .addComponent(reportsbg, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           


    // Variables declaration - do not modify                     
    private javax.swing.JPanel background;
    private javax.swing.JButton envoyer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField requete;
    private javax.swing.JPanel report1;
    private javax.swing.JPanel report2;
    private javax.swing.JPanel sqlreport;
    private javax.swing.JTabbedPane reportPanels;
    private javax.swing.JPanel reportsbg;
    private javax.swing.JLabel title;
    public Connexion conn;
    public ArrayList<String> liste;
    // End of variables declaration     
    
     class Request implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            
           liste = new ArrayList<String>();
            try {
                liste = conn.remplirChampsRequete(requete.getText());
            } catch (SQLException ex) {
                Logger.getLogger(Reporting.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }
    
}

